keys:
  - &hosts:
    - &silvia age1kxfx525c9x5x5ylt9yehc0223r6zv4pkhsjwgdhdx8dq7k8x94ksmy4vcq
    - &stagea age1p74ghnw9x3yt55kawaeaaz8cmrmthlg4j8rd4qqv5dsz8s7jqusshjz4xq
creation_rules:
  - path_regex: hosts/silvia/secrets.ya?ml$
    key_groups:
    - age:
      - *silvia
  - path_regex: hosts/stagea/secrets.ya?ml$
    key_groups:
    - age:
      - *stagea
