keys:
  - &hosts:
    - &stagea age1p74ghnw9x3yt55kawaeaaz8cmrmthlg4j8rd4qqv5dsz8s7jqusshjz4xq
creation_rules:
  - path_regex: ^(hosts/stagea/)?secrets\.ya?ml$
    key_groups:
    - age:
      - *stagea
