{
  home.file.".config/nchat/key.conf" = {
    text = ''
      backspace=KEY_BACKSPACE
      backspace_alt=KEY_ALT_BACKSPACE
      backward_kill_word=\33\177
      backward_word=\4001040
      begin_line=\33\60 #alt 0
      cancel=KEY_CTRLC
      clear=KEY_CTRLC
      copy=\33\171 #alt y
      cut=\33\170
      decrease_list_width=\33\54
      delete=KEY_DC
      delete_chat=\33\144
      delete_line_after_cursor=KEY_CTRLK
      delete_line_before_cursor=KEY_CTRLU
      delete_msg=KEY_CTRLD
      down=KEY_DOWN
      edit_msg=KEY_CTRLZ
      end=KEY_END
      end_line=\33\44 #alt $
      ext_call=\33\164
      ext_edit=\33\145
      find=\33\146 #alt f
      find_next=\33\106 #alt F
      forward_msg=\33\162
      forward_word=\4001057
      goto_chat=\33\107 #alt G
      home=KEY_HOME
      increase_list_width=\33\56
      jump_quoted=\33\161
      kill_word=\4001006
      left=KEY_LEFT
      linebreak=\33\12 #alt enter
      next_chat=\33\116 #alt N
      next_page=KEY_NPAGE
      ok=KEY_RETURN
      open=\33\157 #alt O
      open_link=\33\117 #alt o
      open_msg=\33\167
      other_commands_help=\33\57 #alt /
      paste=\33\160 #alt p
      prev_chat=\33\120 #alt P
      prev_page=KEY_PPAGE
      quit=\33\161 #alt q
      react=\33\163
      right=KEY_RIGHT
      save=KEY_CTRLR
      select_contact=\33\147 #alt g
      select_emoji=\33\56 #alt .
      send_msg=KEY_RETURN
      spell=\33\44
      terminal_focus_in=KEY_FOCUS_IN
      terminal_focus_out=KEY_FOCUS_OUT
      terminal_resize=KEY_RESIZE
      toggle_emoji=\33\43 #alt #
      toggle_help=\33\77 #alt ?
      toggle_list=\33\154 #alt l
      toggle_top=KEY_CTRLP
      transfer=KEY_CTRLT
      unread_chat=\33\165 #alt u
      up=KEY_UP
    '';
  };
}
