{
  imports = [
    ./script-modules.nix
    ./script-opts.nix
    ./auto-next.nix
    ./autoload.nix
    ./chapters.nix
    ./command-palette.nix
    ./end.nix
    ./gallery-thumbgen.nix
    ./inputevent.nix
    ./memo.nix
    ./pause-image.nix
    ./playlist-view.nix
    ./profile-indicator.nix
    ./quality-menu.nix
    ./skip-to-silence.nix
    ./sub-translate.nix
    ./toggle-vapoursynth.nix
    ./uosc-screenshot.nix
    ./uosc-subtitle-settings.nix
    ./uosc-video-settings.nix
    ./youtube-search.nix
    ./youtube-sub.nix
  ];
}
