{config, ...}: let
  base00 = config.colorScheme.palette.base00;
  base01 = config.colorScheme.palette.base01;
  base02 = config.colorScheme.palette.base02;
  base05 = config.colorScheme.palette.base05;
  base0D = config.colorScheme.palette.base0D;
  base0E = config.colorScheme.palette.base0E;
in {
  home.file.".config/nchat/app.conf" = {
    text = ''
      default_color_bg=0x${base00}
      default_color_fg=0x${base01}
      dialog_attr=
      dialog_attr_selected=reverse
      dialog_color_bg=
      dialog_color_fg=0x${base05}
      dialog_shaded_color_bg=
      dialog_shaded_color_fg=gray
      entry_attr=
      entry_color_bg=
      entry_color_fg=
      help_attr=
      help_color_bg=0x${base02}
      help_color_fg=0x${base05}
      history_name_attr=bold
      history_name_attr_selected=reverse
      history_name_recv_color_bg=
      history_name_recv_color_fg=0x${base0D}
      history_name_recv_group_color_bg=
      history_name_recv_group_color_fg=usercolor
      history_name_sent_color_bg=
      history_name_sent_color_fg=0x${base0E}
      history_text_attachment_color_bg=
      history_text_attachment_color_fg=0x${base05}
      history_text_attr=
      history_text_attr_selected=reverse
      history_text_quoted_color_bg=
      history_text_quoted_color_fg=0x${base05}
      history_text_reaction_color_bg=0x${base01}
      history_text_reaction_color_fg=gray
      history_text_recv_color_bg=
      history_text_recv_color_fg=
      history_text_recv_group_color_bg=
      history_text_recv_group_color_fg=
      history_text_sent_color_bg=
      history_text_sent_color_fg=
      list_attr=
      list_attr_selected=reverse
      list_color_bg=
      list_color_fg=0x${base05}
      listborder_attr=
      listborder_color_bg=
      listborder_color_fg=0x${base05}
      status_attr=
      status_color_bg=0x${base02}
      status_color_fg=0x${base0D}
      top_attr=
      top_color_bg=0x${base02}
      top_color_fg=0x${base05}
    '';
  };
}
